version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    environment:
      MONGO_URL: mongodb://mongo:27017
      DB_NAME: amtlich
      FIREBASE_SERVICE_ACCOUNT: '{}'
      ALLOWED_ORIGINS: http://localhost:3000
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    environment:
      REACT_APP_API_URL: http://localhost:8000
      HOST: 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
