name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install backend dependencies
        run: python -m pip install -r backend/requirements.txt
      - name: Run backend tests
        run: pytest
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - name: Install frontend dependencies
        run: yarn install --frozen-lockfile
        working-directory: frontend
      - name: Run frontend tests
        run: yarn test --watchAll=false
        working-directory: frontend
